version: '3.8'  # Use a compatible version for Docker 24.05

services:
  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    container_name: opencmms_app
    volumes:
      - ./app:/app  # Mount the src directory in app to /app in the container
    ports:
      - "8000:8000"
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000  # Command to run the Django server
    #command: tail -f /dev/null # Command to hold the container open for inspection
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1  # Prevent Python from buffering stdout/stderr

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: postgres_db
    environment:
      POSTGRES_DB: your_database_name  # Specify your database name
      POSTGRES_USER: your_username  # Specify your database user
      POSTGRES_PASSWORD: your_password  # Specify your database password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

  nginx:
    image: nginx:latest  # Use the latest Nginx image
    container_name: nginx_proxy
    ports:
      - "80:80"  # Expose port 80 for HTTP
      - "443:443"  # Expose port 443 for HTTPS
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx configuration
      - ./nginx/ssl:/etc/nginx/ssl  # Mount the SSL certificate directory
    depends_on:
      - python  # Ensure the Django service is up before Nginx starts

volumes:
  postgres_data:  # Define a volume for the database
